@database = MECAZON-DB
@collection = users
@domain = http://localhost
@port = 3000
###
GET {{domain}}:{{port}}/all-users/{{database}}/{{collection}}
Content-Type: application/json

###
POST {{domain}}:{{port}}/add-user/{{database}}/{{collection}}
Content-Type: application/json

{
  "document": {
    "name": "Bob",
    "age": 50
  }
}

###
@id = 6758c932a9b8e574e06ef564
DELETE {{domain}}:{{port}}/delete/{{database}}/{{collection}}/{{id}}
Content-Type: application/json